version: '3'
services:
  mial-web:
    container_name: mial-project
    image: asteriskrin/mial-laravel
    volumes:
      - ./src:/var/www/html
    env_file: .env
    dns:
      - 1.1.1.1
      - 1.0.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mial-db
    networks:
      - nginx-proxy-network
networks:
  nginx-proxy-network:
    external: true