version: '3'
services:
  mial-web:
    container_name: mial-project
    image: asteriskrin/mial-laravel
    volumes:
      - ./src:/var/www/html
    env_file: .env
    dns:
      - 1.1.1.1
      - 1.0.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mial-db
    networks:
      - nginx-proxy-network
      - mial-private-network
  mial-db:
    container_name: mial-db
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes: 
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qwerty123
      - MYSQL_PASSWORD=qwerty456
      - MYSQL_USER=root
      - MYSQL_DATABASE=mial_db
    networks:
      - mial-private-network

networks:
  nginx-proxy-network:
    external: true
  mial-private-network:
    driver: bridge